app:
  frontend-base-url: ${APP_FRONTEND_BASE_URL}

spring:
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${SPRING_MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          switch-edu-id:
            client-id: test-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          switch-edu-id:
            issuer-uri: https://auth.dev.si.usi.ch/realms/simurbs

logging:
  level:
    org:
      springframework:
        security: DEBUG
