spring:
  data:
    mongodb:
      database: users_tutorial_lab02
      host: localhost
      port: 27017
  security:
    oauth2:
      client:
        registration:
          switch-edu-id:
            client-id: test-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          switch-edu-id:
            issuer-uri: https://auth.dev.si.usi.ch/auth/realms/simurbs
      resourceserver:
        jwt:
          issuer-uri: https://auth.dev.si.usi.ch/auth/realms/simurbs

logging:
  level:
    org:
      springframework:
        security: DEBUG
