services:
  mongodb:
    image: mongo:6
    networks: [ lab-05-network ]
    restart: always

  backend:
    image: ${BACKEND_IMAGE}
    container_name: lab-05-backend
    networks: [ lab-05-network ]
    depends_on:
      - mongodb
    environment:
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/users_tutorial_lab02
      - APP_FRONTEND_BASE_URL=https://hajime.sa4.si.usi.ch
      - REPLAY_SCRIPT_PATH=/backend/anticheat/replay.bundle.mjs

networks:
  lab-05-network:
    external: true
    name: lab-05-network
